#!/bin/bash
if [ ! $1 ]; then
	echo "usage: downloadsdk 3.9.0"
	exit 0;
fi
wget -r -np -nH -P ./temp "http://192.168.1.200/sdk/$1"
find ./temp -name 'index.html*' | xargs rm 
if [ -d $MMR_DEV_ROOT/sdk.bak ];then
	rm -rf $MMR_DEV_ROOT/sdk.bak
fi
mv $MMR_DEV_ROOT/sdk $MMR_DEV_ROOT/sdk.bak
mv ./temp/sdk/$1 $MMR_DEV_ROOT/sdk
rm -rf ./temp
