#!/bin/sh
adb -e shell input text "$1"
adb -e shell input keyevent 61
adb -e shell input text "$2"
adb -e shell input keyevent 61
adb -e shell input text "$2"
adb -e shell input keyevent 61
adb -e shell input text "$3"
